version: "3"

services:
  consul-server-1:
    image: consul:latest
    hostname: consul-server-1
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 2 -ui -client 0.0.0.0"

  consul-server-2: &consul-server
    image: consul:latest
    hostname: consul-server-2
    command: "agent -server -retry-join consul-server-1 -ui -client 0.0.0.0"
    ports:
      - "8501:8500"
    depends_on:
      - consul-server-1

  consul-server-3:
    <<: *consul-server
    hostname: consul-server-3
    ports:
      - "8502:8500"

  consul-client:
    image: consul:latest
    hostname: consul-client
    ports:
      - "8504:8500"
    command: "agent -client 0.0.0.0 -retry-join consul-server-1 -retry-join consul-server-2 -retry-join consul-server-3"
    depends_on:
      - consul-server-1

  traefik:
    image: traefik:latest
    command: |
      -c traefik.yml
      --api.insecure=true
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - ./traefik.yml:/traefik.yml
    depends_on:
      - consul-client
