logging:
  level:
    io.github.cepr0: debug
    org:
      springframework:
        web: warn
spring:
  cloud:
    consul:
      discovery:
        instance-id: "${spring.application.name}-${spring.cloud.client.hostname}"
        queryPassing: true
        tags:
          - traefik.enable=true
          - traefik.http.routers."${spring.application.name}".rule=PathPrefix(`/demo/${demo.route}`)
